### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by appanp** [AtomLinter/linter-rst#2]
**Atom Version**: 0.189.0
**System**: Mac OS X 10.9.5
**Thrown From**: [linter-rst](https://github.com/AtomLinter/linter-rst) package, v0.0.3

### Stack Trace

Failed to activate the linter package

```
At Cannot find module '/Users/appanponnappan/.atom/packages/linter-rst/lib/linter-rst'

Error: Cannot find module '/Users/appanponnappan/.atom/packages/linter-rst/lib/linter-rst'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at LinterInitializer.activate (/Users/appanponnappan/.atom/packages/linter/lib/init.coffee:73:28)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:461:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:445:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:343:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:423:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:622:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:52:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
.ipynb_checkpoints, vundefined
angularjs, v0.1.0
atom-backbone, v0.6.0
atom-django, v0.2.1
atom-jasmine, v0.5.0
atom-jshint, v1.5.0
atom-language-xquery, v0.2.0
atom-python-debugger, v0.2.2
atomatigit, v1.2.3
build, v0.26.0
codeship-status, v0.1.1
coffee-refactor, v0.6.2
color-picker, v1.5.0
elixir-cmd, v0.2.5
emmet, v2.3.4
git-tab-status, v1.6.0
ide-haskell, v0.3.6
javascript-snippets, v1.0.0
language-FBP, v0.1.0
language-chef, v0.4.0
language-dot, v1.5.0
language-elixir, v0.3.4
language-fsharp, v0.8.4
language-gherkin, v1.0.1
language-groovy, v0.3.0
language-haskell, v1.0.0
language-iced-coffeescript, v0.1.0
language-ipynb, v1.3.0
language-javascript-semantic, v0.1.0
language-latex, v0.4.1
language-powershell, v2.0.0
language-python-django-templates, v0.1.0
language-r, v0.1.1
language-restructuredtext, v0.3.0
language-scala, v1.1.0
language-sml, v0.2.0
language-swift, v0.3.0
linter, v0.12.0
linter-clang, v2.25.1
linter-coffeelint, v0.2.0
linter-cpplint, v0.1.3
linter-hlint, v0.3.1
linter-pylama, v0.0.17
linter-rst, v0.0.3
linter-scalac, v0.3.3
markdown-format, v2.5.0
minimap, v4.6.0
processing-language, v0.1.0
refactor, v0.4.1
rest-client, v0.3.1
script, v2.18.0
travis-ci-status, v0.13.0
vim-mode, v0.40.0
web-view, v0.3.0

# Dev
No dev packages
```

**Comment by alem0lars** [comment]
:+1:

**Comment by 00krishna** [comment]
+1

**Comment by steelbrain** [comment]
This package was never implemented
